[project]
name = "ke-utils"
version = "0.1.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.26.3",
    "pandas>=2.2.3",
    "scipy>=1.14.1",
    "urllib3>=1.26.13",
    "pymongo>=4.10.1",
    "torch>=2.0.0",
    "sortedcontainers>=2.4.0",
    "requests>=2.28.1",
    "multi-choices-parser>=0.10.0",
    "transformers>=4.48.3",
    "accelerate>=1.3.0",
    "openai<=1.52.2",
    "xxhash>=3.5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

