[project]
name = "lm-tools"
version = "0.1.3"
description = "A set of utilitary classes and functions to make it easier to use Huggingface Language Models"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ke-utils",
    "protobuf>=5.28.3",
    "sentencepiece>=0.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
  "tests"
]
